// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykhwyjepxzsczsepivyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraHd5amVweHpzY3pzZXBpdnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTM5MzksImV4cCI6MjA2NDQ2OTkzOX0.qeigh9eFNr0uxeG9ISW3qwkLyfqpU34UaAl7MWUsgv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);